/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkap.views.internalFrame;

import bkap.dao.impl.UserDAO;
import bkap.model.User;
import bkap.utils.Helper;
import bkap.utils.Security;
import bkap.utils.SystemConstant;
import bkap.utils.Utils;
import bkap.views.LoginDialog;
import com.toedter.calendar.demo.DemoTable;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.Date;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author THUY
 */
public class AccountDetailsIF extends javax.swing.JInternalFrame {

    public static final int WIDTH_1 = 250;
    public static final int HEIGHT_1 = 250;
    private UserDAO userDAO = new UserDAO();
    private User user = null;
    private List<User> listUser;

    private String pathDirImage = "src\\bkap\\images\\users\\";
    private String pathFileImage = "";
    private File fileImg = null;
    private String image = "";
    private int userId = 0;

    /**
     * Creates new form AccountDetails
     */
    public AccountDetailsIF() {
        Utils.setIconIF(this, Helper.getResources("tAccount"));
        initComponents();

        listUser = userDAO.findByUsername(LoginDialog.username);
        user = listUser.get(0);
        userId = user.getId();
        setValueFields();
        setNameLabelAndButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        lbFullname = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        lbUsername = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtPhone = new javax.swing.JTextField();
        lbPhone = new javax.swing.JLabel();
        lbMale = new javax.swing.JRadioButton();
        lbFemale = new javax.swing.JRadioButton();
        lbGender = new javax.swing.JLabel();
        lbBirthday = new javax.swing.JLabel();
        txtBirthday = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lbAddress = new javax.swing.JLabel();
        btnChooseImage = new javax.swing.JButton();
        lbAvartar = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        msgInformation = new javax.swing.JLabel();
        containImg = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Tài khoản");

        lbFullname.setText("Họ và tên");

        lbUsername.setText("Username");

        lbPassword.setText("Password");

        lbPhone.setText("Số điện thoại");

        buttonGroupGender.add(lbMale);
        lbMale.setText("Nam");

        buttonGroupGender.add(lbFemale);
        lbFemale.setText("Nữ");

        lbGender.setText("Giới tính");

        lbBirthday.setText("Ngày sinh");

        txtBirthday.setDateFormatString("dd-MM-yyyy");

        txtAddress.setColumns(20);
        txtAddress.setRows(2);
        jScrollPane1.setViewportView(txtAddress);

        lbAddress.setText("Địa chỉ");

        btnChooseImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/images/icon/icons8_folder_20px.png"))); // NOI18N
        btnChooseImage.setText("Chọn ảnh");
        btnChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseImageActionPerformed(evt);
            }
        });

        lbAvartar.setText("Ảnh đại diện");

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/images/icon/icons8_edit_20px.png"))); // NOI18N
        btnUpdate.setText("Lưu");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        containImg.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(msgInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdate))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbAddress)
                                .addGap(70, 70, 70)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbGender)
                                    .addComponent(lbBirthday))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbMale)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbFemale))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbAvartar)))))
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnChooseImage)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(containImg, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbUsername)
                        .addComponent(lbFullname)
                        .addComponent(lbPassword)
                        .addComponent(lbPhone))
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFullname, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addComponent(txtUsername)
                        .addComponent(txtPassword)
                        .addComponent(txtPhone))
                    .addContainerGap(238, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(containImg, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbGender)
                            .addComponent(lbMale)
                            .addComponent(lbFemale))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbBirthday)
                            .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChooseImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAvartar)
                        .addGap(17, 17, 17)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAddress)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(msgInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbFullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtUsername)
                        .addComponent(lbUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbPassword)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbPhone)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(257, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseImageActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter imgFilter = new FileNameExtensionFilter("jpeg", "jpg", "png");

        fileChooser.setFileFilter(imgFilter);
        fileChooser.setMultiSelectionEnabled(false);

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            fileImg = fileChooser.getSelectedFile();
            pathFileImage = fileImg.getAbsolutePath();
            // set image
            Utils.setImage(containImg, pathFileImage);
        }
    }//GEN-LAST:event_btnChooseImageActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        String fullname = txtFullname.getText();
        String username = txtUsername.getText();
        String phone = txtPhone.getText();
        String password = txtPassword.getText().toString();
        String address = txtAddress.getText();
        Date birthday = txtBirthday.getDate();

        if (fullname.isEmpty()) {
            Utils.setMessageInformation(msgInformation, "Vui lòng nhập họ và tên!", false);
        } else if (!fullname.matches("^[a-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ\\s\\W|_]+$")) {
            Utils.setMessageInformation(msgInformation, "Vui lòng họ tên không nhập kí tự đặc biệt!", false);
        } else if (username.isEmpty()) {
            Utils.setMessageInformation(msgInformation, "Vui lòng nhập tên tài khoản!", false);
        } else if (password.isEmpty()) {
            Utils.setMessageInformation(msgInformation, "Vui lòng nhập mật khẩu!", false);
        } else if (phone.isEmpty()) {
            Utils.setMessageInformation(msgInformation, "Vui lòng nhập số điện thoại!", false);
        } else if (!phone.matches("^[0-9]{10}+$")) {
            Utils.setMessageInformation(msgInformation, "Vui lòng nhập đúng định dạng số điện thoại!", isMaximum);
        } else if (!lbFemale.isSelected() && !lbMale.isSelected()) {
            Utils.setMessageInformation(msgInformation, "Vui lòng chọn giới tính!", false);
        } else {
            user = new User();
            user.setId(userId);
            user.setFullname(fullname);
            user.setUsername(username);
            user.setPassword(Security.encrypt(password, SystemConstant.SECRET_KEY));
            user.setPhone(phone);
            user.setAddress(address);
            user.setBirthday(birthday);
            if (lbFemale.isSelected()) {
                user.setGender(SystemConstant.GENDER_FEMALE);
            } else {
                user.setGender(SystemConstant.GENDER_MALE);
            }
            user.setImage(image);
            saveImage();
            userDAO.updateAccount(user);
            Utils.setMessageInformation(msgInformation, SystemConstant.MSG_SUCCESSFUL_UPDATE, true);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void setValueFields() {
        txtFullname.setText(user.getFullname());
        txtUsername.setText(user.getUsername());
        txtPhone.setText(user.getPhone());
        txtAddress.setText(user.getAddress());
        txtPassword.setText(Security.decrypt(user.getPassword(), SystemConstant.SECRET_KEY));
        if (user.isGender() == SystemConstant.GENDER_MALE) {
            lbMale.setSelected(true);
        } else {
            lbFemale.setSelected(true);
        }
        txtBirthday.setDate(user.getBirthday());
        image = user.getImage();

//        Utils.setImage(containImg, image);
//        Utils.setImage(containImg, image);
//        ImageIcon imgThisImg = new ImageIcon("src\\bkap\\images\\img.jpg");
        ImageIcon imgIcon = new ImageIcon(image);
        Image img = imgIcon.getImage();
        Image newImage = img.getScaledInstance(135, 148, Image.SCALE_SMOOTH);
        imgIcon = new ImageIcon(newImage);

        containImg.setIcon(imgIcon);
    }

    private void saveImage() {
        if (!pathFileImage.isEmpty()) {
            File dir = new File(pathDirImage);
            if (dir.exists()) {
                Path sourceDirectory = Paths.get(pathFileImage);
                Path targetDirectory = Paths.get(pathDirImage + sourceDirectory.getFileName());
                image = pathDirImage + sourceDirectory.getFileName().toString();
                try {
                    //copy source to target using Files Class
                    Files.copy(sourceDirectory, targetDirectory, StandardCopyOption.REPLACE_EXISTING);
                } catch (IOException ex) {
                    Logger.getLogger(UserIF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        }
    }

    private void setNameLabelAndButton() {
        lbAddress.setText(Helper.getResources("address"));
        lbAvartar.setText(Helper.getResources("avatar"));
        lbBirthday.setText(Helper.getResources("birthday"));
        lbFemale.setText(Helper.getResources("female"));
        lbFullname.setText(Helper.getResources("fullname"));
        lbGender.setText(Helper.getResources("gender"));
        lbMale.setText(Helper.getResources("male"));
        lbPassword.setText(Helper.getResources("password"));
        lbPhone.setText(Helper.getResources("phone"));
        lbUsername.setText(Helper.getResources("username"));

        btnChooseImage.setText(Helper.getResources("chooseImg"));
        btnUpdate.setText(Helper.getResources("update"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseImage;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JLabel containImg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbAvartar;
    private javax.swing.JLabel lbBirthday;
    private javax.swing.JRadioButton lbFemale;
    private javax.swing.JLabel lbFullname;
    private javax.swing.JLabel lbGender;
    private javax.swing.JRadioButton lbMale;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JLabel msgInformation;
    private javax.swing.JTextArea txtAddress;
    private com.toedter.calendar.JDateChooser txtBirthday;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
