/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkap.views.internalFrame;

import bkap.dao.impl.CuponDAO;
import bkap.model.Cupon;
import bkap.utils.Helper;
import bkap.utils.SystemConstant;
import bkap.utils.Utils;
import bkap.views.LoginDialog;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import javax.rmi.CORBA.Util;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hongb
 */
public class CuponIF extends javax.swing.JInternalFrame {

    private List<Cupon> listCupon;
    private CuponDAO cuponDAO = new CuponDAO();

    private DefaultTableModel modelCupon;

    private int indexSelected = 0;
    private int idCupon;
    private int statusCupon = SystemConstant.STATUS_ON;

    private String name;
    private String discount;
    private String maxQuantity;
    private String status;
    private String descript;
    private Date startDate = null;
    private Date endDate = null;
    private Date createdAt = Utils.getCurrentTime();
    private Date updatedAt = null;

    /**
     * Creates new form CuponIF
     */
    public CuponIF() {
        Utils.setIconIF(this, Helper.getResources("tCupon"));
        initComponents();
        cuponDAO.updateStatus();
        listCupon = cuponDAO.findAll();

        modelCupon = (DefaultTableModel) tblCupon.getModel();

        setDataTable(modelCupon, listCupon);
        setDataCombox();

        if (LoginDialog.levelUser == SystemConstant.LEVEL_USER) {
            btnAdd.setEnabled(false);
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
        }
        setNameLabelAndButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNameCupon = new javax.swing.JLabel();
        txtNameCupon = new javax.swing.JTextField();
        lbQuantity = new javax.swing.JLabel();
        txtMaxQuantity = new javax.swing.JTextField();
        lbEndDate = new javax.swing.JLabel();
        lbStartDate = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCupon = new javax.swing.JTable();
        txtStartDate = new com.toedter.calendar.JDateChooser();
        txtEndDate = new com.toedter.calendar.JDateChooser();
        messageInformation = new javax.swing.JLabel();
        lbDiscount = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnSearch = new javax.swing.JButton();
        txtKeySearch = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();
        btnRefresh = new javax.swing.JButton();
        lbDescript = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescript = new javax.swing.JTextPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mã giảm giá");

        lbNameCupon.setText("Mã giảm giá");

        lbQuantity.setText("Số lượng");

        lbEndDate.setText("Ngày kết thúc");

        lbStartDate.setText("Ngày bắt đầu");

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/images/icon/icons8_remove_20px.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/images/icon/icons8_edit_20px.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/images/icon/icons8_add_20px.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblCupon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã giảm giá", "Số lượng", "Discount", "Ngày bắt đầu", "Ngày kết thúc", "Mô tả", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCupon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCuponMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCupon);

        txtStartDate.setDateFormatString("dd-MM-yyyy");

        txtEndDate.setDateFormatString("dd-MM-yyyy");

        lbDiscount.setText("Discount");

        jLabel6.setText("%");

        jSeparator1.setBackground(new java.awt.Color(240, 240, 240));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/images/icon/icons8_search_20px.png"))); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtKeySearch.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        txtKeySearch.setForeground(new java.awt.Color(153, 153, 153));
        txtKeySearch.setText("Mã giảm giá");
        txtKeySearch.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtKeySearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKeySearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKeySearchFocusLost(evt);
            }
        });

        cbStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbStatusItemStateChanged(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkap/images/icon/icons8_refresh_20px.png"))); // NOI18N
        btnRefresh.setText("Làm mới");
        btnRefresh.setPreferredSize(new java.awt.Dimension(85, 25));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        lbDescript.setText("Mô tả");

        jScrollPane2.setViewportView(txtDescript);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(messageInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKeySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbStartDate)
                                    .addComponent(lbNameCupon)
                                    .addComponent(lbDiscount)
                                    .addComponent(lbDescript))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNameCupon)
                                            .addComponent(txtStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbEndDate)
                                            .addComponent(lbQuantity))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtMaxQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane2))))
                        .addGap(31, 31, 31)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNameCupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNameCupon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbStartDate)
                            .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaxQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDiscount)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescript)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd)
                        .addComponent(btnUpdate)
                        .addComponent(btnDelete))
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtKeySearch, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (checkValidate()) {
            statusCupon = SystemConstant.STATUS_ON;
            Cupon c = setPropertiesForObject();            
            cuponDAO.add(c);
            Utils.setMessageInformation(messageInformation, SystemConstant.MSG_SUCCESSFUL_UPDATE, true);

            setNullValueFields();
            listCupon = cuponDAO.findAll();
            setDataTable(modelCupon, listCupon);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblCuponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCuponMouseClicked
        messageInformation.setText("");
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        btnAdd.setEnabled(false);

        indexSelected = tblCupon.getSelectedRow();

        if (indexSelected == -1) {
            Utils.setMessageInformation(messageInformation, SystemConstant.MSG_ERROR_CHOOSE_ROW_TABLE, false);
        } else {
            Cupon c = listCupon.get(indexSelected);
            idCupon = c.getId();
            txtNameCupon.setText(c.getName());
            txtMaxQuantity.setText((int) c.getMaxQuantity() + "");
            txtDescript.setText(c.getDescript());
            statusCupon = c.getStatus();
            txtDiscount.setText(c.getDiscount() + "");
            txtStartDate.setDate(c.getStartDate());
            txtEndDate.setDate(c.getEndDate());
            createdAt = c.getCreatedAt();
        }
    }//GEN-LAST:event_tblCuponMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int reply = JOptionPane.showConfirmDialog(rootPane, SystemConstant.CONFIRM_DELETE);

        if (reply == 0) {
            cuponDAO.delete(idCupon);
            Utils.setMessageInformation(messageInformation, SystemConstant.MSG_SUCCESSFUL_UPDATE, true);

            setNullValueFields();
            listCupon = cuponDAO.findAll();
            setDataTable(modelCupon, listCupon);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int reply = JOptionPane.showConfirmDialog(rootPane, SystemConstant.CONFIRM_UPDATE);

        if (reply == 0) {
            if (checkValidate()) {
                Cupon c = setPropertiesForObject();
                cuponDAO.edit(c);
                Utils.setMessageInformation(messageInformation, SystemConstant.MSG_SUCCESSFUL_UPDATE, true);

                setNullValueFields();
                listCupon = cuponDAO.findAll();
                setDataTable(modelCupon, listCupon);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cbStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbStatusItemStateChanged
        String keySearch = txtKeySearch.getText();
        if (cbStatus.getSelectedItem().toString() == "Tất cả") {
            listCupon = cuponDAO.findAll();
            txtKeySearch.setText("Mã giảm giá");
            txtKeySearch.setForeground(new Color(153, 153, 153));
        } else if (cbStatus.getSelectedItem().toString() == SystemConstant.STATUS_TXT_CUPON_ON && keySearch.equals("Mã giảm giá")) {
            listCupon = cuponDAO.findByStatus(SystemConstant.STATUS_CUPON_ON);
        } else if (cbStatus.getSelectedItem().toString() == SystemConstant.STATUS_TXT_CUPON_OFF && keySearch.equals("Mã giảm giá")) {
            listCupon = cuponDAO.findByStatus(SystemConstant.STATUS_CUPON_OFF);
        } else if (!keySearch.isEmpty()) {
            if (cbStatus.getSelectedItem().toString() == SystemConstant.STATUS_TXT_CUPON_OFF) {
                listCupon = cuponDAO.findByNameAndStatus(keySearch, SystemConstant.STATUS_CUPON_OFF);
            } else {
                listCupon = cuponDAO.findByNameAndStatus(keySearch, SystemConstant.STATUS_CUPON_ON);
            }
        }
        if (listCupon.isEmpty()) {
            Utils.setMessageInformation(messageInformation, SystemConstant.ERROR_NO_RESULT, false);
        } else {
            messageInformation.setText("");
        }
        setDataTable(modelCupon, listCupon);
    }//GEN-LAST:event_cbStatusItemStateChanged

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        setNullValueFields();
        listCupon = cuponDAO.findAll();
        setDataTable(modelCupon, listCupon);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keySearch = txtKeySearch.getText();
        if (keySearch.equals("Mã giảm giá")) {
            Utils.setMessageInformation(messageInformation, "Vui lòng nhập mã phòng để tìm kiếm!", false);
        } else {
            listCupon = cuponDAO.findByName(keySearch);
            if (listCupon.isEmpty()) {
                Utils.setMessageInformation(messageInformation, "Không tìm thấy mã giảm giá!", false);
            }
            setDataTable(modelCupon, listCupon);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtKeySearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKeySearchFocusLost
        if (txtKeySearch.getText().equals("")) {
            txtKeySearch.setText("Mã giảm giá");
            txtKeySearch.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtKeySearchFocusLost

    private void txtKeySearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKeySearchFocusGained
        if (txtKeySearch.getText().equals("Mã giảm giá")) {
            txtKeySearch.setText("");
            txtKeySearch.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtKeySearchFocusGained

    private void setDataCombox() {
        cbStatus.addItem("Tất cả");
        cbStatus.addItem(SystemConstant.STATUS_TXT_CUPON_ON);
        cbStatus.addItem(SystemConstant.STATUS_TXT_CUPON_OFF);
    }

    private void getValueOfFields() {
        name = txtNameCupon.getText();
        discount = txtDiscount.getText();
        maxQuantity = txtMaxQuantity.getText();
        startDate = txtStartDate.getDate();
        descript = txtDescript.getText();
        endDate = txtEndDate.getDate();
    }

    private boolean checkValidate() {
        boolean check = false;
        getValueOfFields();
        if (!name.matches("[A-Z0-9]{2,}")) {
            Utils.setMessageInformation(messageInformation, "Vui lòng nhập đúng định dạng mã giảm giá, VD: TET2021", false);
        } else if (startDate == null && endDate == null && maxQuantity.isEmpty()) {
            Utils.setMessageInformation(messageInformation, "Vui lòng nhập số mã giảm giá giới hạn hoặc nhập thời gian bắt đầu!", check);
        } else if (discount.isEmpty()) {
            Utils.setMessageInformation(messageInformation, "Vui lòng nhập giá trị mã giảm giá!", false);
        } else if (descript.isEmpty()) {
            Utils.setMessageInformation(messageInformation, "Vui lòng nhập mô tả!", false);
        } else {
            check = true;
        }
        return check;
    }

    private Cupon setPropertiesForObject() {
        Cupon c = new Cupon();
        c.setId(idCupon);
        c.setName(name);
        c.setMaxQuantity(Integer.parseInt(maxQuantity));
        c.setDiscount(Float.parseFloat(discount));
        c.setDescript(descript);
        c.setStartDate(startDate);
        c.setEndDate(endDate);
        c.setCreatedAt(createdAt);
        c.setUpdatedAt(Utils.getCurrentTime());
        c.setStatus(statusCupon);
        return c;
    }

    private void setNullValueFields() {
        txtNameCupon.setText("");
        txtMaxQuantity.setText("");
        txtDiscount.setText("");
        txtStartDate.setDate(null);
        txtEndDate.setDate(null);
        txtDescript.setText("");

        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        btnAdd.setEnabled(true);
        txtKeySearch.setText("Mã giảm giá");
        txtKeySearch.setForeground(new Color(153, 153, 153));
    }

    private void setDataTable(DefaultTableModel model, List<Cupon> list) {
        model.setRowCount(0);
        for (Cupon c : list) {
            model.addRow(new Object[]{
                c.getName(), c.getMaxQuantity(), c.getDiscount(), c.getStartDate(), c.getEndDate(), c.getDescript(), c.getStatus() == SystemConstant.STATUS_CUPON_ON ? SystemConstant.STATUS_TXT_CUPON_ON : SystemConstant.STATUS_TXT_CUPON_OFF
            });
        }
    }

    private void setNameLabelAndButton() {
        lbDiscount.setText(Helper.getResources("discount"));
        lbEndDate.setText(Helper.getResources("endDate"));
        lbNameCupon.setText(Helper.getResources("nameCupon"));
        lbQuantity.setText(Helper.getResources("quantity"));
        lbStartDate.setText(Helper.getResources("startDate"));
        lbDescript.setText(Helper.getResources("descript"));

        btnAdd.setText(Helper.getResources("add"));
        btnDelete.setText(Helper.getResources("delete"));
        btnRefresh.setText(Helper.getResources("refresh"));
        btnSearch.setText(Helper.getResources("search"));
        btnUpdate.setText(Helper.getResources("update"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbDescript;
    private javax.swing.JLabel lbDiscount;
    private javax.swing.JLabel lbEndDate;
    private javax.swing.JLabel lbNameCupon;
    private javax.swing.JLabel lbQuantity;
    private javax.swing.JLabel lbStartDate;
    private javax.swing.JLabel messageInformation;
    private javax.swing.JTable tblCupon;
    private javax.swing.JTextPane txtDescript;
    private javax.swing.JTextField txtDiscount;
    private com.toedter.calendar.JDateChooser txtEndDate;
    private javax.swing.JTextField txtKeySearch;
    private javax.swing.JTextField txtMaxQuantity;
    private javax.swing.JTextField txtNameCupon;
    private com.toedter.calendar.JDateChooser txtStartDate;
    // End of variables declaration//GEN-END:variables
}
